name: Github Action for LaTeX
on: [push]

jobs:
  refresh_drive:
    environment: DRIVE_ENV_SEC
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
      - name: Delete File from Google Drive
        env:
          DRIVE_ENV_SEC: ${{ secrets.DRIVE_ENV_SEC }}
        run: python delete_gdrive_file.py
  build_latex_Algebra:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document Algebra
        uses: xu-cheng/latex-action@v3
        with:
          work_in_root_file_dir: true
          root_file: Algebra/algebra_notes.tex
      - name: Upload Algebra file
        uses: actions/upload-artifact@v3
        with:
          name: Algebra
          path: Algebra/algebra_notes.pdf
          if-no-files-found: error
      - name: Upload Algebra to Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
        with:
          target: Algebra/algebra_notes.pdf
          credentials: ${{ secrets.DRIVESHHHH }}
          parent_folder_id: 1aS3fF7XhO1DM_PM8ZS4mqTBwxi8FWGoc

  build_latex_Category:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document Category Theory
        uses: xu-cheng/latex-action@v3
        with:
          work_in_root_file_dir: true
          root_file: CategoryTheory/category_theory.tex
      - name: Upload Category Theory file
        uses: actions/upload-artifact@v3
        with:
          name: Category Theory
          path: CategoryTheory/category_theory.pdf
          if-no-files-found: error
      - name: Upload Category Theory to Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
        with:
          target: CategoryTheory/category_theory.pdf
          credentials: ${{ secrets.DRIVESHHHH }}
          parent_folder_id: 1aS3fF7XhO1DM_PM8ZS4mqTBwxi8FWGoc

  build_latex_AlgebraII:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document AlgebraII
        uses: xu-cheng/latex-action@v3
        with:
          work_in_root_file_dir: true
          root_file: AlgebraII/algebraII_notes.tex
      - name: Upload Algebra II file
        uses: actions/upload-artifact@v3
        with:
          name: Algebra II
          path: AlgebraII/algebraII_notes.pdf
          if-no-files-found: error
      - name: Upload Algebra II to Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
        with:
          target: AlgebraII/algebraII_notes.pdf
          credentials: ${{ secrets.DRIVESHHHH }}
          parent_folder_id: 1aS3fF7XhO1DM_PM8ZS4mqTBwxi8FWGoc

  build_latex_Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document Analysis
        uses: xu-cheng/latex-action@v3
        with:
          work_in_root_file_dir: true
          root_file: Analysis/analysis_notes.tex
      - name: Upload Analysis file
        uses: actions/upload-artifact@v3
        with:
          name: Analysis
          path: Analysis/analysis_notes.pdf
          if-no-files-found: error
      - name: Upload Analysis to Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
        with:
          target: Analysis/analysis_notes.pdf
          credentials: ${{ secrets.DRIVESHHHH }}
          parent_folder_id: 1aS3fF7XhO1DM_PM8ZS4mqTBwxi8FWGoc

  build_latex_PhysicsI:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document PhysicsI
        uses: xu-cheng/latex-action@v3
        with:
          work_in_root_file_dir: true
          root_file: PhysicsI/physics_notes.tex
      - name: Upload Physics I file
        uses: actions/upload-artifact@v3
        with:
          name: Physics I
          path: PhysicsI/physics_notes.pdf
          if-no-files-found: error
      - name: Upload Physics I to Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
        with:
          target: PhysicsI/physics_notes.pdf
          credentials: ${{ secrets.DRIVESHHHH }}
          parent_folder_id: 1aS3fF7XhO1DM_PM8ZS4mqTBwxi8FWGoc

  build_latex_PhysicsII:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document PhysicsII
        uses: xu-cheng/latex-action@v3
        with:
          work_in_root_file_dir: true
          root_file: PhysicsII/physicsII_notes.tex
      - name: Upload Physics II file
        uses: actions/upload-artifact@v3
        with:
          name: Physics II
          path: PhysicsII/physicsII_notes.pdf
          if-no-files-found: error
      - name: Upload Physics II to Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
        with:
          target: PhysicsII/physicsII_notes.pdf
          credentials: ${{ secrets.DRIVESHHHH }}
          parent_folder_id: 1aS3fF7XhO1DM_PM8ZS4mqTBwxi8FWGoc

  build_latex_ComplexAnalysis:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document ComplexAnalysis
        uses: xu-cheng/latex-action@v3
        with:
          work_in_root_file_dir: true
          root_file: ComplexAnalysis/complex.tex
      - name: Upload Complex Analysis file
        uses: actions/upload-artifact@v3
        with:
          name: Complex Analysis
          path: ComplexAnalysis/complex.pdf
          if-no-files-found: error
      - name: Upload Complex Analysis to Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
        with:
          target: ComplexAnalysis/complex.pdf
          credentials: ${{ secrets.DRIVESHHHH }}
          parent_folder_id: 1aS3fF7XhO1DM_PM8ZS4mqTBwxi8FWGoc

  build_latex_Calculus1:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document Calculus1
        uses: xu-cheng/latex-action@v3
        with:
          work_in_root_file_dir: true
          root_file: Calculus1/exercícios_de_cálculo.tex
      - name: Upload Calculus I file
        uses: actions/upload-artifact@v3
        with:
          name: Calculus I
          path: Calculus1/exercícios_de_cálculo.pdf
          if-no-files-found: error
      - name: Upload Calculus I to Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
        with:
          target: Calculus1/exercícios_de_cálculo.pdf
          credentials: ${{ secrets.DRIVESHHHH }}
          parent_folder_id: 1aS3fF7XhO1DM_PM8ZS4mqTBwxi8FWGoc

  build_latex_MetricSpaces:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document MetricSpaces
        uses: xu-cheng/latex-action@v3
        with:
          work_in_root_file_dir: true
          root_file: MetricSpaces/metric_notes.tex
      - name: Upload Metric Spaces file
        uses: actions/upload-artifact@v3
        with:
          name: Metric Spaces
          path: MetricSpaces/metric_notes.pdf
          if-no-files-found: error
      - name: Upload Metric Spaces to Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
        with:
          target: MetricSpaces/metric_notes.pdf
          credentials: ${{ secrets.DRIVESHHHH }}
          parent_folder_id: 1aS3fF7XhO1DM_PM8ZS4mqTBwxi8FWGoc

  build_latex_MeasureTheory:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document MeasureTheory
        uses: xu-cheng/latex-action@v3
        with:
          work_in_root_file_dir: true
          root_file: MeasureTheory/measure_theory.tex
      - name: Upload Measure Theory file
        uses: actions/upload-artifact@v3
        with:
          name: Measure Theory
          path: MeasureTheory/measure_theory.pdf
          if-no-files-found: error
      - name: Upload Measure Theory to Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
        with:
          target: MeasureTheory/measure_theory.pdf
          credentials: ${{ secrets.DRIVESHHHH }}
          parent_folder_id: 1aS3fF7XhO1DM_PM8ZS4mqTBwxi8FWGoc

  build_latex_Probability:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document Probability
        uses: xu-cheng/latex-action@v3
        with:
          work_in_root_file_dir: true
          root_file: "Probability/*.tex"
      - name: Upload Probability file
        uses: actions/upload-artifact@v3
        with:
          name: Probability
          path: Probability/probability_notes.pdf
          if-no-files-found: error
      - name: Upload Probability to Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
        with:
          target: Probability/probability_notes.pdf
          credentials: ${{ secrets.DRIVESHHHH }}
          parent_folder_id: 1aS3fF7XhO1DM_PM8ZS4mqTBwxi8FWGoc
  build_latex_LinearAlgebra:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document LinearAlgebra
        uses: xu-cheng/latex-action@v3
        with:
          work_in_root_file_dir: true
          root_file: LinearAlgebra/linear_algebra_notes.tex
      - name: Upload Linear Algebra file
        uses: actions/upload-artifact@v3
        with:
          name: Algebra Linear
          path: LinearAlgebra/linear_algebra_notes.pdf
          if-no-files-found: error
      - name: Upload Linear Algebra to Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
        with:
          target: LinearAlgebra/linear_algebra_notes.pdf
          credentials: ${{ secrets.DRIVESHHHH }}
          parent_folder_id: 1aS3fF7XhO1DM_PM8ZS4mqTBwxi8FWGoc
