name: Github Action for LaTeX
on:   
  push:
    tags:
      - '*.*.*'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: |
          Algebra/algebra_notes.tex
          Analysis/analysis_notes.tex
          PhysicsI/physics_notes.tex
          PhysicsII/physicsII_notes.tex
          ComplexAnalysis/complex.tex
          Calculus1/exercícios_de_cálculo.tex
          LinearAlgebra/linear_algebra_notes.tex
          MetricSpaces/metric_notes.tex
          Probability/probability_notes.tex
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Algebra file
      uses: actions/upload-artifact@v3
      with: 
        name: 
          Algebra
        path: 
          algebra_notes.pdf
        if-no-files-found: error
    - name: Upload Release asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release_outputs.upload_url }}
        asset_path: algebra_notes.pdf
        asset_name: algebra_notes.pdf
        asset_content_type: pdf
    - name: Upload Analysis file
      uses: actions/upload-artifact@v3
      with: 
        name: 
          Analise
        path: 
          analysis_notes.pdf
        if-no-files-found: error
    - name: Upload Physics I file
      uses: actions/upload-artifact@v3
      with: 
        name: 
          Fisica I
        path: 
          physics_notes.pdf
        if-no-files-found: error
    - name: Upload Metrics file
      uses: actions/upload-artifact@v3
      with: 
        name: 
          Espaços Metricos 
        path: 
          metric_notes.pdf
        if-no-files-found: error
    - name: Upload Complex Analysis file
      uses: actions/upload-artifact@v3
      with: 
        name: 
          Funções de Variável Complexa
        path: 
          complex.pdf
        if-no-files-found: error
    - name: Upload Probability file
      uses: actions/upload-artifact@v3
      with: 
        name: 
          Probabilidade
        path: 
          probability_notes.pdf
        if-no-files-found: error
    - name: Upload Physics II file
      uses: actions/upload-artifact@v3
      with: 
        name: 
          Física II
        path: 
          physicsII_notes.pdf
        if-no-files-found: error
    - name: Upload Calculus I file
      uses: actions/upload-artifact@v3
      with: 
        name: 
          Calculo I
        path: 
          exercícios_de_cálculo.pdf
        if-no-files-found: error
    - name: Upload Linear Algebra file
      uses: actions/upload-artifact@v3
      with: 
        name: 
          Algebra Linear
        path: 
          linear_algebra_notes.pdf
        if-no-files-found: error
