name: Github Action for LaTeX
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: |
          Algebra/algebra_notes.tex
          Analysis/analysis_notes.tex
    - name: Upload Algebra file
      uses: actions/upload-artifact@v3
      with: 
        name: 
          Algebra
        path: 
          algebra_notes.pdf
        if-no-files-found: error
    - name: Upload Analysis file
      uses: actions/upload-artifact@v3
      with: 
        name: 
          Analysis
        path: 
          analysis_notes.pdf
        if-no-files-found: error
