name: Github Action for LaTeX
on:   
  [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: |
          Algebra/algebra_notes.tex
          Analysis/analysis_notes.tex
          PhysicsI/physics_notes.tex
          PhysicsII/physicsII_notes.tex
          ComplexAnalysis/complex.tex
          Calculus1/exercícios_de_cálculo.tex
          LinearAlgebra/linear_algebra_notes.tex
          MetricSpaces/metric_notes.tex
          Probability/probability_notes.tex
    - name: Upload Algebra file
      uses: actions/upload-artifact@v3
      with: 
        name: 
          Algebra
        path: 
          algebra_notes.pdf
        if-no-files-found: error
    - name: Upload Analysis file
      uses: actions/upload-artifact@v3
      with: 
        name: 
          Analise
        path: 
          analysis_notes.pdf
        if-no-files-found: error
    - name: Upload Physics I file
      uses: actions/upload-artifact@v3
      with: 
        name: 
          Fisica I
        path: 
          physics_notes.pdf
        if-no-files-found: error
    - name: Upload Metrics file
      uses: actions/upload-artifact@v3
      with: 
        name: 
          Espaços Metricos 
        path: 
          metric_notes.pdf
        if-no-files-found: error
    - name: Upload Complex Analysis file
      uses: actions/upload-artifact@v3
      with: 
        name: 
          Funções de Variável Complexa
        path: 
          complex.pdf
        if-no-files-found: error
    - name: Upload Probability file
      uses: actions/upload-artifact@v3
      with: 
        name: 
          Probabilidade
        path: 
          probability_notes.pdf
        if-no-files-found: error
    - name: Upload Physics II file
      uses: actions/upload-artifact@v3
      with: 
        name: 
          Física II
        path: 
          physicsII_notes.pdf
        if-no-files-found: error
    - name: Upload Calculus I file
      uses: actions/upload-artifact@v3
      with: 
        name: 
          Calculo I
        path: 
          exercícios_de_cálculo.pdf
        if-no-files-found: error
    - name: Upload Linear Algebra file
      uses: actions/upload-artifact@v3
      with: 
        name: 
          Algebra Linear
        path: 
          linear_algebra_notes.pdf
        if-no-files-found: error    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
    - name: Delete file from Google Drive
      run: python delete_gdrive_file.py
      env:
        GDRIVE_SERVICE_ACCOUNT_CREDS: |
          ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiY2xhc3Nlc3Bk
          ZnMiLAogICJwcml2YXRlX2tleV9pZCI6ICJhODlkZWUzZjQ2ZWNhYzJhMjMwY2NiZWFlNDMyZWE1
          MWZhMzVjMDAzIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t
          XG5NSUlFdlFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLY3dnZ1NqQWdFQUFvSUJBUURrQ2Z1
          TVFBLzlNb1h4XG5vOURWWlQ4RkQyMU95SXNsVG0rZFI0dHI2Q1ROSWdPU1VieFhYcVJaL3M4NHpv
          NFRXMHNCa1hQdTNTWnJCTGNTXG4xWVRmRkx4MTZYeXdvWWZBNGFlOTJ2cm9UWjRtRWkrNlJSbkdF
          S0poRFpua3FIN2xyeFFvUWVUbU5Dc21BcXQzXG5JRlJYL3ZycXArUEhadDBZdkp3Zk1kakNvTnpE
          R255dkZIQnNZNi9qVmh5a3NYK1ZLTCt3YTd6aGtsWnFjRXpNXG5UMWVpL1JVeVBzQ2F5S3dMa3Rx
          N3ZNaER0eklTeG5GWDZockQ5TUJTbWtFTm1TWDNKQ0VPY0FCdCt0RllUSG8wXG5KaUtrZ2ZYd0FT
          d1ZvL2FsZnQ3bFVJMm50NFdPS1ExdDBNVjBKS0xaSWdwTHY3UUZGY2FkZG5CQm5NdUZVV0dHXG5J
          czhCWHZlZkFnTUJBQUVDZ2dFQWF3dDBsWVdNKytJM2xoSzcrVEFwd1FwWTJWNnlVclRiR0ExNW1S
          SEVGTGNlXG56aFNvUUtzZ28wNUZuL2oySUlmK1VhSWh0Y01DUWNKWTNmSjFDUE1HOUtMQjhYZ2g3
          Wnovek5ONmJJbmk3eVFpXG5XMklNa3psRHdDTk9WbFB5SFlkdUF1Zkx0M1JOdk80TDUwTzUxQVRS
          YkUyYlV3TXFUbTViS3htUEV1M0lNNXpjXG5aWHY3Q1V4NFJzcS9tcVMxankxclM3d29Bd0ZsL2I5
          WnNQR0ZYaFh2TkJGQmh4RitDMWdFa3dmbkdHdHN5bEdRXG52cHRWMGtweDloYkc3bmxvS2NIVk5T
          OVRQU0dlWXVQa2x3YXozckQ2UlQyN2w0L0xET0tteFEvaXdGcEFaeDRWXG5seEM1UHVvOWlEbzk2
          U054c2NvUkMwQVFuYVdFQ09JcWZIVEM4S3dSWVFLQmdRRDZrSTZMU1cwMXZMRE5iSkF0XG5ZSnda
          SSs2a2s0T20vdkFLVnc4QzNlYmJ6OEZ4bDFmLzdhS25WcWtmdDhpSmtLamR5YlYxMWdDNkNvNTNJ
          V0NnXG4zdkVWZmllY1d4QUpnZzQvVWNKeWEzZTFxTEVURXJBZFloTklsWUNjK3AzekVvVHp0clZw
          a3JhcU0vNURZZmRVXG5rTGhuQkVkUzlteERLL0Q0RVlXWFhyQndKUUtCZ1FEby9GWGtqMkRZVW4y
          MmZqb21pUkg0NjlMR09yMXRPTXU1XG5EV2dXbUhUZ3VuV3NSdk9iM2RpaW5ER2hqYzcrVm1SUTh3
          OStjQkNNV2dPZ0VuOFl5anBQWCtvT1N2OE9PMWlRXG5ORmcyeVA1VHFtZDlsd3VvMDd1VFVZVmh2
          dDIzNG5rVzZPSUoxWjRRdVMzNldEOGN6bkFPYjk0SUhCc2RycEhRXG5KenN5TXE4TGN3S0JnSE5o
          eS9KQ0hzTkhIOWVJN1orbnhGb2pYTXAyajRLQUZVTjlzWkR0WkZqR2c5cnVDWHoyXG5EaGVtNVh5
          UW9nMFBDMlFPZGJ4TWpzc2MvMXZHaC91c2pqSUtoTzBRVmdNNjI1cTI2S2JON0RNLytrTEJNVTVt
          XG5rbUN6VDZWNkZ2QVBFQ0EyZTdXZzlQTE52SUdGQkdMeHZhamFwSW1FcG5nTUxRdmU3YmkxeHVQ
          dEFvR0JBTHQwXG4yNzhNUllXSHliSWRtYmdMclRRMHVkL1l2elN6NytZeWpUOHc1MGt4ZlNCaDdm
          dkk0VmJraVdKTThQRGVuZFFyXG4zSm1FblN2ditON0FReGExRDNseDJLWXJYVkFjRzhQYStlY0tq
          T2JRUW5oZ0lYZHk5SWN4bmpucEVnZXo1bTJ5XG5icnd1N2dEU25kWEJUdlprZXZDQ3ZZaVU1SlJi
          TXVMaHpkVXp4bmRWQW9HQVZSQnNickF5Vk4yN3NEYzZpTTVqXG5mUEtOVHNTOWFoR0ZHbCtoYm1Z
          RE9pVWVBeERsN25NWGZXMENmRTZEYW9YL1JWaXUxcXNka1hlaHN0RGtoWXgyXG5lQzdLeUxveEho
          SSthckxDd0JwNFJDcHdzS2lOTzdXWithTWlINE85YlZucER1NjdvZHJSaHVaMGJta2lrTEdGXG5E
          OU5BZUNoUHE5N2NPb2pjTnhWTDd1ST1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAg
          ImNsaWVudF9lbWFpbCI6ICJkcml2ZXJwZGZzQGNsYXNzZXNwZGZzLmlhbS5nc2VydmljZWFjY291
          bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEwNjE1ODc0MzU3NzQ3NzYzMzUxMyIsCiAgImF1dGhf
          dXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9r
          ZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9w
          cm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRo
          Mi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2ds
          ZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvZHJpdmVycGRmcyU0MGNsYXNzZXNwZGZz
          LmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAidW5pdmVyc2VfZG9tYWluIjogImdvb2dsZWFw
          aXMuY29tIgp9Cg== 
#   - name: Create Zip Archive
#     run: |
#       mkdir Artifacts
#       cp algebra_notes.pdf Artifacts/
#       cp analysis_notes.pdf Artifacts/
#       # ... (other cp commands for other PDFs)
#       zip -r Artifacts.zip Artifacts
    - name: Upload Algebra to Google Drive
      uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
      with:
        target: algebra_notes.pdf
        credentials: ${{ secrets.DRIVESHHHH }}
        parent_folder_id: 1aS3fF7XhO1DM_PM8ZS4mqTBwxi8FWGoc
    - name: Upload Analysis to Google Drive
      uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
      with:
        target: analysis_notes.pdf
        credentials: ${{ secrets.DRIVESHHHH }}
        parent_folder_id: 1aS3fF7XhO1DM_PM8ZS4mqTBwxi8FWGoc
    - name: Upload PhysicsII to Google Drive
      uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
      with:
        target: physicsII_notes.pdf
        credentials: ${{ secrets.DRIVESHHHH }}
        parent_folder_id: 1aS3fF7XhO1DM_PM8ZS4mqTBwxi8FWGoc
    - name: Upload Phsyics to Google Drive
      uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
      with:
        target: physics_notes.pdf
        credentials: ${{ secrets.DRIVESHHHH }}
        parent_folder_id: 1aS3fF7XhO1DM_PM8ZS4mqTBwxi8FWGoc
    - name: Upload Linear Algebra to Google Drive
      uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
      with:
        target: linear_algebra_notes.pdf
        credentials: ${{ secrets.DRIVESHHHH }}
        parent_folder_id: 1aS3fF7XhO1DM_PM8ZS4mqTBwxi8FWGoc   
    - name: Upload Probability to Google Drive
      uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
      with:
        target: probability_notes.pdf
        credentials: ${{ secrets.DRIVESHHHH }}
        parent_folder_id: 1aS3fF7XhO1DM_PM8ZS4mqTBwxi8FWGoc
    - name: Upload Complex Variables to Google Drive
      uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
      with:
        target: complex.pdf
        credentials: ${{ secrets.DRIVESHHHH }}
        parent_folder_id: 1aS3fF7XhO1DM_PM8ZS4mqTBwxi8FWGoc
    - name: Upload Metric Spaces to Google Drive
      uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
      with:
        target: metric_notes.pdf
        credentials: ${{ secrets.DRIVESHHHH }}
        parent_folder_id: 1aS3fF7XhO1DM_PM8ZS4mqTBwxi8FWGoc
    - name: Upload Calculus I to Google Drive
      uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
      with:
        target: exercícios_de_cálculo.pdf
        credentials: ${{ secrets.DRIVESHHHH }}
        parent_folder_id: 1aS3fF7XhO1DM_PM8ZS4mqTBwxi8FWGoc
