name: Github Action for LaTeX
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
     -run: bats -v
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: ../../*/*.tex
    - name: Upload PDF file
      uses: actions/upload-artifact@v3
      with: 
        name: PDF
        path: ./*/*.pdf
